### ISSUE TITLE
LEDs when disabled to communicate placement for auto prior to a match (Alice's idea, https://youtu.be/aRY7PFJ0PF0?si=lLZTNuQqeonhHped)

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#141]

**Comment by AlenaNguyen** [comment]
Rotation (4 LEDs on the edge):
	- BLUE = need to rotate clockwise
	- RED = need to rotate counterclockwise
(Edited) Translation (4 LEDs in the middle):
	- Move Y Positive = YELLOW
	- Move Y Negative = PURPLE
	- Move X Positive = RED (towards red alliance)
	- Move X Negative = BLUE (towards blue alliance)

**Comment by alicekuznetsov** [comment]
> Rotation (4 LEDs on the edge): - blue = need to rotate clockwise - red = need to rotate counterclockwise Translation (4 LEDs in the middle) - 2 LEDs lit in the direction you need to move it (blue?)

For the "(blue?)" you could manage x-axis movement based on alliance color. Ex. If you need to go closer to the red alliance, shine red. 
Not sure how that would account for y-axis movement though. No matter what we decide, we need to make a good diagram for it
