### ISSUE TITLE
Create full functional checklist

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#18]

**Comment by AlenaNguyen** [comment]
- Drive
  - Reset yaw
  - Translation
  - Rotation
  - Slow speed
  - Defense mode
  - Snapping (up, down, right, left)
- Climb (up and down)

- Intake Game Piece
- Intake from Source
- Eject Game Piece
- Presets (Amp, Subwoofer, Trap)
- Shoot
- Manual Turret
- LEDs (Amplify, Co-Op, Panic)
