### ISSUE TITLE
Rework Autos 

### ISSUE THREAD

**Issue by alicekuznetsov** [FRCTeam3255/2024_Robot_Code#187]
Basically, all of the autonomous logic in #164 should be removed and reworked. There shouldn't be a need for another transfer command. It may work by only using TransferGamePiece now; small bugs piled up in our autos and TransferAuto was one of many band-aid fixes. I can't give further details without seeing our robot logs (which are all currently on the robot)

We should start from the ground up. Choreo has an official release with event markers now; do we want to try those out? It would be a little more time in the short term but would make high-level autonomous path editing way easier.

Things we need to work on:
- More starting positions for auto. This was a huge issue in playoffs

**Comment by TaylerUva** [comment]
See #170
