### ISSUE TITLE
Add more Presets for Shooting

### ISSUE THREAD

**Issue by Hyrumthehotscott** [FRCTeam3255/2024_Robot_Code#204]
tuning time - potentially more presets
Shooter Subsystem

**Comment by TaylerUva** [comment]
Related to #237

**Comment by TaylerUva** [comment]
We should use the numpad controller to have different preset zones

**Comment by alicekuznetsov** [comment]
![image](https://github.com/FRCTeam3255/2024_Robot_Code/assets/90939494/86d88165-e756-43e1-939d-b0a967385975)
Peninsula Preset

![image](https://github.com/FRCTeam3255/2024_Robot_Code/assets/90939494/77581b52-dd5d-4294-b6eb-164a4cff99f3)
Panama Canal Preset

![image](https://github.com/FRCTeam3255/2024_Robot_Code/assets/90939494/30518965-b227-45cb-bd9c-1ca62d2eac4e)
254-style shuffling #217 

- and Maybe a spike mark preset?

**Comment by TaylerUva** [comment]
I think we also want front of podium (protected)
and
A preset roughly 34” away from subwoofer (in case there is a dead robot at the subwoofer. So we can go up to their bumpers and shoot with a robot between us and the sub)

**Comment by AlenaNguyen** [comment]
> A preset roughly 34” away from subwoofer (in case there is a dead robot at the subwoofer. So we can go up to their bumpers and shoot with a robot between us and the sub)

i'm calling that the leapfrog preset

**Comment by TaylerUva** [comment]
1. Sub (already have)
- need to test if it works for all 3 angles otherwise we need more than one
2. Touching podium
3. Inline with speaker and behind centerline (touching)
