### ISSUE TITLE
Climb command for prep trap should not be while held

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#271]

**Comment by alicekuznetsov** [comment]
Why not? Don't we want to end the prep trap command early in the event of a misclick?

**Comment by TaylerUva** [comment]
> Why not? Don't we want to end the prep trap command early in the event of a misclick? 

That's a good point. It just seemed confusing for the Driver during testing. We can keep it as is but think a small discussion would be good
