### ISSUE TITLE
🚨 VALIDATE INTAKE PIVOT WORKS WIHOUT STARTING CONFIG HARDSTOPS 🚨

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#272]
Staring config hard stops were removed for the climber upgrades. Make sure it doesn't break starting config.

**Comment by alicekuznetsov** [comment]
i think this may be an urgent issue (/j)
i was about to suggest we add a zero intake button... i guess not anymore?

**Comment by TaylerUva** [comment]
> i think this may be an urgent issue (/j)
> 
> i was about to suggest we add a zero intake button... i guess not anymore?

We could "zero" to floor hardstops (might be good emergency)
